version: "3"
services:
  mongodb:
    image: mongo:3.2-jessie
    ports:
      - "27017:27017"
    volumes:
      - "data:/data/db"
  webapp:
    image: arsnova/cards-webapp
    build:
      context: ./cards-webapp
    ports:
      - "3000:3000"
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://@mongodb:27017/meteor
    env_file: webapp.env
  nginx:
    image: arsnova/cards-nginx
    build: ./cards-nginx
    ports:
      - "80:80"
    links:
      - webapp
    depends_on:
      - webapp
volumes:
  data:
